force-app/main/default/objects/Program_Contact_Assignment__c/Program_Contact_Assignment__c.object-meta.xml
<CustomObject>
    <label>Program Contact Assignment</label>
    <nameField>
        <displayFormat>PCA-{0000}</displayFormat>
        <label>Program Contact Assignment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Contact Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Contact_Assignment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Associated Programs</relationshipLabel>
    <relationshipName>Program_Task_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Program_Contact_Assignment__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <formula>Training_Program__r.Duration_in_days__c +   Start_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Program_Contact_Assignment__c/fields/Time_Taken__c.field-meta.xml
<CustomField>
    <fullName>Time_Taken__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Time Taken</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Program_Contact_Assignment__c/fields/Training_Program__c.field-meta.xml
<CustomField>
    <fullName>Training_Program__c</fullName>
    <label>Training Program</label>
    <referenceTo>Training_Program__c</referenceTo>
    <relationshipLabel>Associated Contacts</relationshipLabel>
    <relationshipName>Program_Task_Assignments1</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Program_Contact_Assignment__c/fields/Week__c.field-meta.xml
<CustomField>
    <fullName>Week__c</fullName>
    <formula>IF(TODAY() &gt;= Start_Date__c, (TODAY() - Start_Date__c) /7 + 1, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Week</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Training_Program__c/Training_Program__c.object-meta.xml
<CustomObject>
    <label>Training Program</label>
    <nameField>
        <label>Training Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Training_Program__c/fields/Expected_Duration_In_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Expected_Duration_In_Minutes__c</fullName>
    <label>Expected Duration (In Minutes)</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ProgressTrackerController.cls
public with sharing class ProgressTrackerController {
    @AuraEnabled(cacheable=true)
    public static List<Program_Contact_Assignment__c> populateTable(Id contactId, String searchText){
        List<Program_Contact_Assignment__c> result = new List<Program_Contact_Assignment__c>();

        if(String.isblank(searchText)){
            result = [SELECT Training_Program__c, Training_Program__r.Name, Start_Date__c, End_Date__c, Week__c, Time_Taken__c, Training_Program__r.Expected_Duration_In_Minutes__c		 
                        FROM Program_Contact_Assignment__c 
                        WHERE Contact__c = :contactId];
        } else {
            String filterText = '%' + searchText + '%';
            result = [SELECT Training_Program__c, Training_Program__r.Name, Start_Date__c, End_Date__c, Week__c, Time_Taken__c, Training_Program__r.Expected_Duration_In_Minutes__c	 
                        FROM Program_Contact_Assignment__c 
                        WHERE Contact__c = :contactId and Training_Program__r.Name like :filterText];
        }
        
        return result;
    }
}