force-app/main/default/objects/Contact/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact_Task_Assignment__c/Contact_Task_Assignment__c.object-meta.xml
<CustomObject>
    <label>Contact Task Assignment</label>
    <nameField>
        <displayFormat>CTA-{0000}</displayFormat>
        <label>Contact Task Assignment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Task Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Task_Assignment__c/fields/Associated_Program__c.field-meta.xml
<CustomField>
    <fullName>Associated_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associated Program</label>
    <referenceTo>Training_Program__c</referenceTo>
    <relationshipLabel>Contact Task Assignments</relationshipLabel>
    <relationshipName>Contact_Task_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Task_Assignment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Associated Tasks</relationshipLabel>
    <relationshipName>Contact_Task_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact_Task_Assignment__c/fields/Due_Day__c.field-meta.xml
<CustomField>
    <fullName>Due_Day__c</fullName>
    <inlineHelpText>By which day in the training schedule should the employee complete this task?</inlineHelpText>
    <label>Due Day</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact_Task_Assignment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact_Task_Assignment__c/fields/Time_Taken__c.field-meta.xml
<CustomField>
    <fullName>Time_Taken__c</fullName>
    <formula>TEXT( FLOOR(Time_Taken_In_Minutes__c / 60) ) &amp; &quot;H &quot; &amp; TEXT(MOD(Time_Taken_In_Minutes__c,60)) &amp; &quot;M&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Time Taken</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Task_Assignment__c/fields/Training_Task__c.field-meta.xml
<CustomField>
    <fullName>Training_Task__c</fullName>
    <label>Training Task</label>
    <referenceTo>Training_Task__c</referenceTo>
    <relationshipLabel>Associated Contacts</relationshipLabel>
    <relationshipName>Contact_Task_Assignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Program_Contact_Assignment__c/Program_Contact_Assignment__c.object-meta.xml
<CustomObject>
    <label>Program Contact Assignment</label>
    <nameField>
        <displayFormat>PCA-{0000}</displayFormat>
        <label>Program Contact Assignment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Contact Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Contact_Assignment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Associated Programs</relationshipLabel>
    <relationshipName>Program_Task_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Program_Contact_Assignment__c/fields/Time_Taken__c.field-meta.xml
<CustomField>
    <fullName>Time_Taken__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Time Taken</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Program_Contact_Assignment__c/fields/Training_Program__c.field-meta.xml
<CustomField>
    <fullName>Training_Program__c</fullName>
    <label>Training Program</label>
    <referenceTo>Training_Program__c</referenceTo>
    <relationshipLabel>Associated Contacts</relationshipLabel>
    <relationshipName>Program_Task_Assignments1</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Training_Program__c/Training_Program__c.object-meta.xml
<CustomObject>
    <label>Training Program</label>
    <nameField>
        <label>Training Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Training_Program__c/fields/Duration_in_days__c.field-meta.xml
<CustomField>
    <fullName>Duration_in_days__c</fullName>
    <label>Duration in days</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Training_Program__c/fields/Expected_Duration_In_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Expected_Duration_In_Minutes__c</fullName>
    <label>Expected Duration (In Minutes)</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Training_Task__c/Training_Task__c.object-meta.xml
<CustomObject>
    <label>Training Task</label>
    <nameField>
        <label>Training Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Training_Task__c/fields/Expected_Duration_In_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Expected_Duration_In_Minutes__c</fullName>
    <label>Expected Duration (In Minutes)</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Training_Task__c/fields/Task_Type__c.field-meta.xml
<CustomField>
    <fullName>Task_Type__c</fullName>
    <label>Task Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Conference</fullName>
            </value>
            <value>
                <fullName>Meeting</fullName>
            </value>
            <value>
                <fullName>Module</fullName>
            </value>
            <value>
                <fullName>Optional</fullName>
            </value>
            <value>
                <fullName>Presentation</fullName>
            </value>
            <value>
                <fullName>Project</fullName>
            </value>
            <value>
                <fullName>Task</fullName>
            </value>
            <value>
                <fullName>Trail</fullName>
            </value>
            <value>
                <fullName>Video</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContactTaskAutomationLogicTest.cls
@isTest
private class ContactTaskAutomationLogicTest {
    @TestSetup
    static void makeContactTaskAssignment(){
        Training_Task__c dummyTrainingTask = new Training_Task__c();
        dummyTrainingTask.Expected_Duration_In_Minutes__c = 12;
        dummyTrainingTask.Task_Type__c = 'Meeting';
        insert dummyTrainingTask;  
        
        Training_Task__c dummyTrainingTask2 = new Training_Task__c();
        dummyTrainingTask2.Expected_Duration_In_Minutes__c = 15;
        dummyTrainingTask2.Task_Type__c = 'Meeting';
        insert dummyTrainingTask2; 

        Contact dummyContact = new Contact();
        dummyContact.LastName = 'Smith';
        dummyContact.Start_Date__c = Date.today();
        insert dummyContact;

        Training_Program__c dummyProgram = new Training_Program__c();
        dummyProgram.Name = 'First Program';
        dummyProgram.Duration_in_days__c = 5; 
        insert dummyProgram;

        List<Contact_Task_Assignment__c> testCtaList = new List<Contact_Task_Assignment__c>();
        Contact_Task_Assignment__c testCta = new Contact_Task_Assignment__c();
        testCta.Associated_Program__c = dummyProgram.Id;
        testCta.Contact__c = dummyContact.Id;
        testCta.Due_Day__c = Date.today();
        testCta.Training_Task__c = dummyTrainingTask.Id;
        testCta.Status__c = 'Not Started';
        testCtaList.add(testCta);

        Contact_Task_Assignment__c testCta2 = new Contact_Task_Assignment__c();
        testCta2.Associated_Program__c = dummyProgram.Id;
        testCta2.Contact__c = dummyContact.Id;
        testCta2.Due_Day__c = Date.today();
        testCta2.Training_Task__c = dummyTrainingTask2.Id;
        testCta2.Status__c = 'Not Started';
        testCtaList.add(testCta2);
        insert testCtaList;

        Program_Contact_Assignment__c manipulatedPca = new Program_Contact_Assignment__c();
        manipulatedPca.Start_Date__c = Date.today();
        manipulatedPca.Training_Program__c = dummyProgram.Id;
        manipulatedPca.Contact__c = dummyContact.Id;
        manipulatedPca.Time_Taken__c = 0;
        insert manipulatedPca;
    }

    @isTest 
    static void testSingleRecordUpdateTime() {
        Contact_Task_Assignment__c singleCta = [SELECT Id, Associated_Program__c, Contact__c, Due_Day__c, Training_Task__c, Status__c
                                                        FROM Contact_Task_Assignment__c 
                                                        LIMIT 1];
        singleCta.Status__c = 'Complete';
        update singleCta;

        Program_Contact_Assignment__c updatedPca = [SELECT Id, Time_Taken__c, Contact__c, Training_Program__c
                                                        FROM Program_Contact_Assignment__c
                                                        LIMIT 1];
        System.assertEquals(12, updatedPca.Time_Taken__c);
    }

    @isTest 
    static void testCheckForSubtraction() {
        Contact_Task_Assignment__c singleCta = [SELECT Id, Associated_Program__c, Contact__c, Due_Day__c, Training_Task__c, Status__c
                                                        FROM Contact_Task_Assignment__c 
                                                        LIMIT 1];
        singleCta.Status__c = 'Complete';
        update singleCta;
        singleCta.Status__c = 'In Progress';
        update singleCta;

        Program_Contact_Assignment__c updatedPca = [SELECT Id, Time_Taken__c, Contact__c, Training_Program__c
                                                        FROM Program_Contact_Assignment__c
                                                        LIMIT 1];
        System.assertEquals(0, updatedPca.Time_Taken__c);
    }

    @isTest 
    static void testMultipleRecordUpdateTime() {
        List<Contact_Task_Assignment__c> ctaList = new List<Contact_Task_Assignment__c>();
        List<Contact_Task_Assignment__c> multiCta = [SELECT Id, Associated_Program__c, Contact__c, Due_Day__c, Training_Task__c, Status__c
                                                        FROM Contact_Task_Assignment__c];
        for(Contact_Task_Assignment__c cta:multiCta){
            cta.Status__c = 'Complete';
            ctaList.add(cta);
        }
        update ctaList;

        Program_Contact_Assignment__c updatedPca = [SELECT Id, Time_Taken__c, Contact__c, Training_Program__c
                                                        FROM Program_Contact_Assignment__c
                                                        LIMIT 1];
        System.assertEquals(27, updatedPca.Time_Taken__c);
    }
}