force-app/main/default/objects/Program_Task_Assignment__c/Program_Task_Assignment__c.object-meta.xml
<CustomObject>
    <label>Program Task Assignment</label>
    <nameField>
        <displayFormat>PTA-{0000}</displayFormat>
        <label>Program Task Assignment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Task Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Task_Assignment__c/fields/Training_Program__c.field-meta.xml
<CustomField>
    <fullName>Training_Program__c</fullName>
    <label>Training Program</label>
    <referenceTo>Training_Program__c</referenceTo>
    <relationshipLabel>Associated Tasks</relationshipLabel>
    <relationshipName>Program_Task_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Program_Task_Assignment__c/fields/Training_Task__c.field-meta.xml
<CustomField>
    <fullName>Training_Task__c</fullName>
    <label>Training Task</label>
    <referenceTo>Training_Task__c</referenceTo>
    <relationshipLabel>Associated Programs</relationshipLabel>
    <relationshipName>Program_Task_Assignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Training_Program__c/Training_Program__c.object-meta.xml
<CustomObject>
    <label>Training Program</label>
    <nameField>
        <label>Training Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Training_Program__c/fields/Expected_Duration_In_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Expected_Duration_In_Minutes__c</fullName>
    <label>Expected Duration (In Minutes)</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Training_Task__c/Training_Task__c.object-meta.xml
<CustomObject>
    <label>Training Task</label>
    <nameField>
        <label>Training Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Training_Task__c/fields/Expected_Duration_In_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Expected_Duration_In_Minutes__c</fullName>
    <label>Expected Duration (In Minutes)</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TrainingProgramAutomationLogicHandler.cls
public with sharing class TrainingProgramAutomationLogicHandler {
    public static void updateTimeNeeded(List<Training_Program__c> trainingProgramTrigger) {
        Decimal expectedDuration = 0;
        Training_Program__c triggeredProgram = trainingProgramTrigger[0];
        Id currTrainingProgram = triggeredProgram.ID;
    
        List<Program_Task_Assignment__c> programTaskList = [SELECT Training_Program__c, Training_Task__c
                                                            FROM Program_Task_Assignment__c
                                                            WHERE Training_Program__c= :currTrainingProgram];
                                                            
        List<Training_Task__c> trainingTaskList = [SELECT id, Expected_Duration_In_Minutes__c
                                                    FROM Training_Task__c];
    
        for (Program_Task_Assignment__c pta : programTaskList){
            for (Training_Task__c training:trainingTaskList){
                if (pta.Training_Task__c == training.id){
                    expectedDuration += training.Expected_Duration_In_Minutes__c;
                }
            }
        }
    
        triggeredProgram.Expected_Duration_In_Minutes__c = expectedDuration;
    }
}