force-app/main/default/objects/Contact_Task_Assignment__c/Contact_Task_Assignment__c.object-meta.xml
<CustomObject>
    <label>Contact Task Assignment</label>
    <nameField>
        <displayFormat>CTA-{0000}</displayFormat>
        <label>Contact Task Assignment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Task Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Task_Assignment__c/fields/Associated_Program__c.field-meta.xml
<CustomField>
    <fullName>Associated_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associated Program</label>
    <referenceTo>Training_Program__c</referenceTo>
    <relationshipLabel>Contact Task Assignments</relationshipLabel>
    <relationshipName>Contact_Task_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Task_Assignment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Associated Tasks</relationshipLabel>
    <relationshipName>Contact_Task_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact_Task_Assignment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact_Task_Assignment__c/fields/Time_Taken__c.field-meta.xml
<CustomField>
    <fullName>Time_Taken__c</fullName>
    <formula>TEXT( FLOOR(Time_Taken_In_Minutes__c / 60) ) &amp; &quot;H &quot; &amp; TEXT(MOD(Time_Taken_In_Minutes__c,60)) &amp; &quot;M&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Time Taken</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Task_Assignment__c/fields/Training_Task__c.field-meta.xml
<CustomField>
    <fullName>Training_Task__c</fullName>
    <label>Training Task</label>
    <referenceTo>Training_Task__c</referenceTo>
    <relationshipLabel>Associated Contacts</relationshipLabel>
    <relationshipName>Contact_Task_Assignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Program_Contact_Assignment__c/Program_Contact_Assignment__c.object-meta.xml
<CustomObject>
    <label>Program Contact Assignment</label>
    <nameField>
        <displayFormat>PCA-{0000}</displayFormat>
        <label>Program Contact Assignment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Contact Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Contact_Assignment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Associated Programs</relationshipLabel>
    <relationshipName>Program_Task_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Program_Contact_Assignment__c/fields/Time_Taken__c.field-meta.xml
<CustomField>
    <fullName>Time_Taken__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Time Taken</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Program_Contact_Assignment__c/fields/Training_Program__c.field-meta.xml
<CustomField>
    <fullName>Training_Program__c</fullName>
    <label>Training Program</label>
    <referenceTo>Training_Program__c</referenceTo>
    <relationshipLabel>Associated Contacts</relationshipLabel>
    <relationshipName>Program_Task_Assignments1</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Training_Program__c/Training_Program__c.object-meta.xml
<CustomObject>
    <label>Training Program</label>
    <nameField>
        <label>Training Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Training_Program__c/fields/Expected_Duration_In_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Expected_Duration_In_Minutes__c</fullName>
    <label>Expected Duration (In Minutes)</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Training_Task__c/Training_Task__c.object-meta.xml
<CustomObject>
    <label>Training Task</label>
    <nameField>
        <label>Training Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Training_Task__c/fields/Expected_Duration_In_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Expected_Duration_In_Minutes__c</fullName>
    <label>Expected Duration (In Minutes)</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ContactTaskAutomationLogicHandler.cls
public with sharing class ContactTaskAutomationLogicHandler {
    public static void updateTimeTaken(List<Contact_Task_Assignment__c> ctaTrigger) {

        Map<Id, Program_Contact_Assignment__c> resultMap = new Map<Id, Program_Contact_Assignment__c>();
        Boolean multiple = false;
        //Decimal needed for multiple apex requests in one trigger
        Decimal myTime = 0;
        if(ctaTrigger.size() > 1){
            multiple = true;
        }

        Set<ID> taskIdSet = new Set<ID>();
        for (Contact_Task_Assignment__c triggeredCta: ctaTrigger){
            taskIdSet.add(triggeredCta.Training_Task__c);
        }

        Map<ID, Training_Task__c> taskMap = new Map<ID, Training_Task__c>(
            [SELECT Expected_Duration_In_Minutes__c
                FROM Training_Task__c
                WHERE Id IN :taskIdSet]
        );
        
        for (Contact_Task_Assignment__c triggeredCta: ctaTrigger){
            ID currTask = triggeredCta.Training_Task__c;
            Program_Contact_Assignment__c pca = programContactAssignmentFetch(triggeredCta);
            Training_Task__c task = taskMap.get(currTask);
            
            //Create a result list to update
            if (triggeredCta.Status__c == 'Complete'){
                //Handle bulk apex change
                if (multiple == true){
                    if (myTime != Null){
                        myTime += task.Expected_Duration_In_Minutes__c;
                    } else {
                        myTime = task.Expected_Duration_In_Minutes__c;
                    }
                    pca.Time_Taken__c = myTime;
                //Handle individual apex change 
                } else {
                    if (pca.Time_Taken__c != Null){
                        pca.Time_Taken__c += task.Expected_Duration_In_Minutes__c;
                    } else {
                        pca.Time_Taken__c = task.Expected_Duration_In_Minutes__c;
                    }
                }
                resultMap.put(pca.Training_Program__c, pca);
            }
        }
        update resultMap.values();
    }

    //Cannot use a map because we do not know the ID in order to get the triggered contact task assignment
    public static void checkForSubtraction(List<Contact_Task_Assignment__c> ctaTrigger, List<Contact_Task_Assignment__c> oldCtaTrigger){
        Contact_Task_Assignment__c triggeredCta = ctaTrigger[0];
        ID currTask = triggeredCta.Training_Task__c;

        Program_Contact_Assignment__c pca = programContactAssignmentFetch(triggeredCta);
        
        List<Training_Task__c> task = [SELECT Expected_Duration_In_Minutes__c
                                        FROM Training_Task__c
                                        WHERE Id = :currTask];

        for(Contact_Task_Assignment__c newCta : ctaTrigger){
            for (Contact_Task_Assignment__c oldCta: oldCtaTrigger){
                if (oldCta.Status__c == 'Complete' && newCta.Status__c != 'Complete'){
                    //Null and zero check
                    if (pca.Time_Taken__c != Null || pca.Time_Taken__c > 0){
                        pca.Time_Taken__c -= task[0].Expected_Duration_In_Minutes__c;
                    }
                }
            }
        }
        update pca;
    }

    private static Program_Contact_Assignment__c programContactAssignmentFetch(Contact_Task_Assignment__c triggeredCta){
        ID currTrainingProgram = triggeredCta.Associated_Program__c;
        ID contact = triggeredCta.Contact__c;

        Program_Contact_Assignment__c pca = [SELECT Training_Program__c, Time_Taken__c
                                                    FROM Program_Contact_Assignment__c
                                                    WHERE Training_Program__c = :currTrainingProgram AND Contact__c=:contact];
        return pca;
    }
}