force-app/main/default/objects/Contact_Task_Assignment__c/Contact_Task_Assignment__c.object-meta.xml
<CustomObject>
    <label>Contact Task Assignment</label>
    <nameField>
        <displayFormat>CTA-{0000}</displayFormat>
        <label>Contact Task Assignment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Task Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Task_Assignment__c/fields/Associated_Program__c.field-meta.xml
<CustomField>
    <fullName>Associated_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associated Program</label>
    <referenceTo>Training_Program__c</referenceTo>
    <relationshipLabel>Contact Task Assignments</relationshipLabel>
    <relationshipName>Contact_Task_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Task_Assignment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Associated Tasks</relationshipLabel>
    <relationshipName>Contact_Task_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact_Task_Assignment__c/fields/Due_Day__c.field-meta.xml
<CustomField>
    <fullName>Due_Day__c</fullName>
    <inlineHelpText>By which day in the training schedule should the employee complete this task?</inlineHelpText>
    <label>Due Day</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact_Task_Assignment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact_Task_Assignment__c/fields/Training_Task__c.field-meta.xml
<CustomField>
    <fullName>Training_Task__c</fullName>
    <label>Training Task</label>
    <referenceTo>Training_Task__c</referenceTo>
    <relationshipLabel>Associated Contacts</relationshipLabel>
    <relationshipName>Contact_Task_Assignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Program_Contact_Assignment__c/Program_Contact_Assignment__c.object-meta.xml
<CustomObject>
    <label>Program Contact Assignment</label>
    <nameField>
        <displayFormat>PCA-{0000}</displayFormat>
        <label>Program Contact Assignment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Contact Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Contact_Assignment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Associated Programs</relationshipLabel>
    <relationshipName>Program_Task_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Program_Contact_Assignment__c/fields/Training_Program__c.field-meta.xml
<CustomField>
    <fullName>Training_Program__c</fullName>
    <label>Training Program</label>
    <referenceTo>Training_Program__c</referenceTo>
    <relationshipLabel>Associated Contacts</relationshipLabel>
    <relationshipName>Program_Task_Assignments1</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Program_Task_Assignment__c/Program_Task_Assignment__c.object-meta.xml
<CustomObject>
    <label>Program Task Assignment</label>
    <nameField>
        <displayFormat>PTA-{0000}</displayFormat>
        <label>Program Task Assignment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Task Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Task_Assignment__c/fields/Due_Day__c.field-meta.xml
<CustomField>
    <fullName>Due_Day__c</fullName>
    <label>Due Day</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Program_Task_Assignment__c/fields/Training_Program__c.field-meta.xml
<CustomField>
    <fullName>Training_Program__c</fullName>
    <label>Training Program</label>
    <referenceTo>Training_Program__c</referenceTo>
    <relationshipLabel>Associated Tasks</relationshipLabel>
    <relationshipName>Program_Task_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Program_Task_Assignment__c/fields/Training_Task__c.field-meta.xml
<CustomField>
    <fullName>Training_Task__c</fullName>
    <label>Training Task</label>
    <referenceTo>Training_Task__c</referenceTo>
    <relationshipLabel>Associated Programs</relationshipLabel>
    <relationshipName>Program_Task_Assignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Training_Program__c/Training_Program__c.object-meta.xml
<CustomObject>
    <label>Training Program</label>
    <nameField>
        <label>Training Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Training_Task__c/Training_Task__c.object-meta.xml
<CustomObject>
    <label>Training Task</label>
    <nameField>
        <label>Training Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ProgramContactAssignmentLogicHandler.cls
public with sharing class ProgramContactAssignmentLogicHandler {

    public static void updateTasks(List<Program_Contact_Assignment__c> ctaTrigger){
        List<Contact_Task_Assignment__c> listToInsert = new List<Contact_Task_Assignment__c>();

        for(Program_Contact_Assignment__c triggeredAssignment : ctaTrigger){
            ID currTrainingProgram= triggeredAssignment.Training_Program__c;
            Date startDate = triggeredAssignment.Start_Date__c;
            List<Program_Task_Assignment__c> programTaskList = [SELECT Training_Program__c, Training_Task__c, Due_Day__c
                                                                FROM Program_Task_Assignment__c 
                                                                WHERE Training_Program__c = :currTrainingProgram];
            if (!programTaskList.isEmpty()){
                for (Program_Task_Assignment__c pta : programTaskList){
                    Contact_Task_Assignment__c currTaskAssignment = new Contact_Task_Assignment__c();
                    currTaskAssignment.Contact__c = triggeredAssignment.Contact__c;
                    currTaskAssignment.Associated_Program__c = currTrainingProgram;
                    currTaskAssignment.Training_Task__c = pta.Training_Task__c;
                    currTaskAssignment.Due_Day__c = startDate.addDays((Integer)pta.Due_Day__c);
                    currTaskAssignment.Status__c = 'Not Started';
                    listToInsert.add(currTaskAssignment);
                }
            }
        }
    
        if(!listToInsert.isEmpty()){
            insert listToInsert;
        }
    }
}